### ISSUE TITLE
Boot screen improvements 

### ISSUE THREAD

**Issue by ghost** [Avdan-OS/Desktop-environment#10]
so someone please remove the logs that come while booting
https://user-images.githubusercontent.com/70370670/169805311-52d1f3e9-90de-4582-80bf-1c78a8c9487a.mp4

user should only see booting animation when they toggle it using a short cut

anyone can comment who can do this assignment, I will assign this issue to you

**Comment by thearctiic** [comment]
As far as I know, Plymouth will not allow you to 100% remove all of the logging from the boot screen. You can reduce it with some basic config and settings, but not entirely remove it without some core changes.

**Comment by ghost** [comment]
Okay

**Comment by ghost** [comment]
> As far as I know, Plymouth will not allow you to 100% remove all of the logging from the boot screen. You can reduce it with some basic config and settings, but not entirely remove it without some core changes.

@projectintel-anon would you like to work on it ??

**Comment by ghost** [comment]
I have one more improvement point, loading animation should be
![boot1](https://user-images.githubusercontent.com/70370670/170699653-c933e177-0e6d-4bdf-9431-67c861f7dd76.gif) and then when loading is over, this should be played 
![boot2](https://user-images.githubusercontent.com/70370670/170699792-fd615898-7843-4b81-b804-7e798b7eac0e.gif)

so it should be like this
https://user-images.githubusercontent.com/70370670/170699955-0641dce8-13ee-4094-b55c-bdc8b12fd163.mp4

anyone can comment who wants to work on it
 

- [x] hiding logs
- [ ] updating animation

**Comment by thearctiic** [comment]
This is a lot harder than it may seem. We will try our best to work on it

**Comment by Froxcey** [comment]
That's not really that doable. What's the difference between booting and loading? When should the animation change specifically. I think it's better to play that zoom cool animation once, then play the normal loading one. It's not that hard to implement using plymouth, just some basic scripting.

**Comment by ghost** [comment]
So, do you wanna work on it ?? @projectintel-anon

**Comment by thearctiic** [comment]
Already working on it

**Comment by ghost** [comment]
Ok

**Comment by Padmanabh82** [comment]
- [ ] hiding logs
- [ ] updating animation

**Comment by ghost** [comment]
> Already working on it

@projectintel-anon whats its status About hiding logs and updating animation ? should i self assign it ? If you don't want to work on it ?

**Comment by thearctiic** [comment]
Your choice :)

**Comment by ghost** [comment]
> Your choice :)

No, if you wanna work on it i wont

**Comment by dorakuflu** [comment]
I managed to hide all logs by using
[grub-silent](https://aur.archlinux.org/packages/grub-silent) instead of grub. Here's my grub config with grub-silent: [link](https://pastebin.pl/view/5d0b1389)

Btw, the the little flickering probably won't happen with a native system. It happens since I'm running a VM and the resolution changes.

https://user-images.githubusercontent.com/108133549/178470764-51994733-160c-47f9-9e22-4cadc50aa565.mp4

**Comment by ghost** [comment]
@dorakuflu can you make a pr ?

**Comment by dorakuflu** [comment]
@Padmanabh82 I can make a pr on the Grub-Theme repo to implement the configuration, but I don't know if they will fully work without grub-silent installed.

**Comment by ghost** [comment]
@dorakuflu so first clone then update and test

**Comment by dorakuflu** [comment]
@Padmanabh82 Found a way without installing grub-silent. Opened a pr on AvdanOS/Grub-Theme. Please take a look.

**Comment by ghost** [comment]
Okay ping us on discord we will provide you a contributer role

**Comment by dorakuflu** [comment]
Anybody working on this? I can't seem to find how we can play the other animation before the display manager. Maybe we play it after the login like it does in KDE?

**Comment by ghost** [comment]
1) no one is working on
2) like a splash screen?
3) would you like to work on it ?

**Comment by dorakuflu** [comment]
Yes, like a splash screen. I'm not sure if a splash screen is needed, but I can't figure out how we can play two different animations at two different stages of boot. So, a splash screen might be our best bet to play the second animation as it's post-boot. I can work on it if that sounds good to you.

**Comment by StoneMcYT** [comment]
The design team is already working on a  fix to the bootscrean and we will keep the logs in there till we move into the beta stage a nd I am decently unsure why this github issue is not properly detailed and lacks details to explain what this is for

**Comment by dorakuflu** [comment]
Well, plymouth records the logs into a file, so this shouldn't be an issue for the design team. This GitHub issue is focused on making the boot clean and stylish.

**Comment by StoneMcYT** [comment]
> Well, plymouth records the logs into a file, so this shouldn't be an issue for the design team. This GitHub issue is focused on making the boot clean and stylish.

Yes when it comes to styling the boot screen which the design team is looking into redooing it

**Comment by dorakuflu** [comment]
> > Well, plymouth records the logs into a file, so this shouldn't be an issue for the design team. This GitHub issue is focused on making the boot clean and stylish.
> 
> Yes when it comes to styling the boot screen which the design team is looking into redooing it

Well if there is a design theme outside of this repo that I am not aware of, I would like to be a part of it. I actively contribute to the Desktop Environment, and I think that things would go much more smoothly if we all could be on the same team.

**Comment by StoneMcYT** [comment]
> > > Well, plymouth records the logs into a file, so this shouldn't be an issue for the design team. This GitHub issue is focused on making the boot clean and stylish.
> > 
> > 
> > Yes when it comes to styling the boot screen which the design team is looking into redooing it
> 
> Well if there is a design theme outside of this repo that I am not aware of, I would like to be a part of it. I actively contribute to the Desktop Environment, and I think that things would go much more smoothly if we all could be on the same team.

hmmm are you in our discord server since most of the design team talks there

**Comment by dorakuflu** [comment]
I am. My username's dorqreis. Is there a channel like this one where the boot screen design is planned?

**Comment by StoneMcYT** [comment]
> I am. My username's dorqreis. Is there a channel like this one where the boot screen design is planned?
Well there is no dedicated planning area but this channel is where the designers are meant to discuss the new boot screen design and man no wonder I couldn't find you you haven't filled a request for the dev role yet
![image](https://user-images.githubusercontent.com/67421882/179726782-2cd42d3f-d603-4eab-97e7-0931d6def85f.png)

**Comment by dorakuflu** [comment]
> > I am. My username's dorqreis. Is there a channel like this one where the boot screen design is planned?
> > Well there is no dedicated planning area but this channel is where the designers are meant to discuss the new boot screen design and man no wonder I couldn't find you you haven't filled a request for the dev role yet
> > ![image](https://user-images.githubusercontent.com/67421882/179726782-2cd42d3f-d603-4eab-97e7-0931d6def85f.png)

Yeah as Goos has mentioned, I didn't have enough commits. I didn't know there was another channel for DE development, so sorry working on the logs. Thanks for the role though, I'm happy you liked my work.

**Comment by StoneMcYT** [comment]
> > > I am. My username's dorqreis. Is there a channel like this one where the boot screen design is planned?
> > > Well there is no dedicated planning area but this channel is where the designers are meant to discuss the new boot screen design and man no wonder I couldn't find you you haven't filled a request for the dev role yet
> > > ![image](https://user-images.githubusercontent.com/67421882/179726782-2cd42d3f-d603-4eab-97e7-0931d6def85f.png)
> 
> Yeah as Goos has mentioned, I didn't have enough commits. I didn't know there was another channel for DE development, so sorry working on the logs. Thanks for the role though, I'm happy you liked my work.

Well you have dev now was an error an error on our part for not checking your comment history don't the destroy environment as at the time both myself and goos didn't actually check your github comment history on this repository.

**Comment by MrSerge01** [comment]
> > > I am. My username's dorqreis. Is there a channel like this one where the boot screen design is planned?
> > > Well there is no dedicated planning area but this channel is where the designers are meant to discuss the new boot screen design and man no wonder I couldn't find you you haven't filled a request for the dev role yet
> > > ![image](https://user-images.githubusercontent.com/67421882/179726782-2cd42d3f-d603-4eab-97e7-0931d6def85f.png)
> 
> Yeah as Goos has mentioned, I didn't have enough commits. I didn't know there was another channel for DE development, so sorry working on the logs. Thanks for the role though, I'm happy you liked my work.

I am sorry, the goos is just dumb. Congrats on your dev role!

**Comment by ghost** [comment]
So i think we don't need this issue now
