### ISSUE TITLE
Biometric login support (Fingerprint + Facial) 

### ISSUE THREAD

**Issue by ghost** [Avdan-OS/Desktop-environment#11]
so, now we also need for facial recognition and fingerprint lock

for help - https://wiki.archlinux.org/title/Fprint , https://itsfoss.com/face-unlock-ubuntu/#:~:text=Just%20run%20the%20sudo%20howdy,tries%20to%20detect%20a%20face.

- [x] fingerprint lock design
- [ ] fingerprint lock implementation
- [x] facial recognition design
- [ ] facial recognition implementation

 anyone can comment who wants to work on it

**Comment by thearctiic** [comment]
The actual logic behind facial recognition and fingerprint locking is possible - I would be able to do this if nobody else wants to, it is possible with something like keras.vggface and other ML modules of Python.

**Comment by Froxcey** [comment]
There's the [Howdy](https://github.com/boltgolt/howdy) package can handle face authentication.

**Comment by thearctiic** [comment]
> There's the [Howdy](https://github.com/boltgolt/howdy) package can handle face authentication.

Wow i've never actually seen this package before, that looks fantastic! I'll put this onto my test build later.

**Comment by ghost** [comment]
> There's the [Howdy](https://github.com/boltgolt/howdy) package can handle face authentication.

Thats what i send a article for

**Comment by ghost** [comment]
@projectintel-anon so, i have assigned it to you. Start Working on algorithm, you will get design soon

**Comment by thearctiic** [comment]
> @projectintel-anon so, i have assigned it to you. Start Working on algorithm, you will get design soon

I already have the algorithm written - its used in one of my apps I am working on

**Comment by Froxcey** [comment]
Btw maybe we can also put suggestions and WIP features on the [project tab](https://github.com/Avdan-OS/Desktop-environment/projects?type=beta)? It's more organized comparing to issues.

**Comment by thearctiic** [comment]
![image](https://user-images.githubusercontent.com/55900441/170384532-7bb68fbf-b6f7-4930-933c-40b867436b42.png)
This worries me a lot (from the Howdy package)

**Comment by ghost** [comment]
> Btw maybe we can also put suggestions and WIP features on the [project tab](https://github.com/Avdan-OS/Desktop-environment/projects?type=beta)? It's more organized comparing to issues. 

Okay, i will check what it is

**Comment by ghost** [comment]
@projectintel-anon any update ??

**Comment by thearctiic** [comment]
> @projectintel-anon any update ??

I am on medical leave as announced yesterday.

Facial recognition is done, we just need to figure out a way to integrate it with our login screen.

Someone else is doing the fingerprint stuff because I don't have a fingerprint sensor.

**Comment by ghost** [comment]
Okay, np! But can you tell who it is ??

**Comment by ghost** [comment]
@projectintel-anon can you send your code, so i can work on it ?

**Comment by thearctiic** [comment]
@Padmanabh82 you mean for the face unlock?

**Comment by ghost** [comment]
> @Padmanabh82 you mean for the face unlock?

Yeah

**Comment by thearctiic** [comment]
> > @Padmanabh82 you mean for the face unlock?
> 
> Yeah

There is no code. It is just installing 'howdy', and adding it to the PAM modules.

**Comment by thearctiic** [comment]
https://gist.github.com/pastleo/76597c6ae8f95bb02982fea6df3a3ade

**Comment by ghost** [comment]
Okay, from now i will work on it

**Comment by Darshan-2021-11** [comment]
I will work on it

**Comment by ghost** [comment]
> I will work on it

Okay you do fingerprint, i am assigning it to you

**Comment by thearctiic** [comment]
What happened to Gamer247 doing fingerprint?

**Comment by ghost** [comment]
> What happened to Gamer247 doing fingerprint?

@projectintel-anon, @Darshan-2021-11 is gamer247. i have assigned issue to it. They are working on fingerprint

**Comment by thearctiic** [comment]
Oh lmao, apologies

**Comment by Trynera** [comment]
doesn't it depend on device? Like don't they each need different drivers

**Comment by ghost** [comment]
@Trynera it will be just like android or windows if device doesnt support it it gets hided

**Comment by dorakuflu** [comment]
I installed the login theme and it asks for an API key to login. Does that only happen to me?

**Comment by ghost** [comment]
@dorakuflu check #23

**Comment by StoneMcYT** [comment]
Dear @Darshan-2021-11  I would like to confirm if you are still actively working on biomatics support for the login screen?

**Comment by StoneMcYT** [comment]
and after skimming this issue again i believe we can use existing packages that allow fingerprint recognition and that allows facial recognition algorithms support and we have to build the interface for both as well as driver support for devices (which there could be existing packages by the mainfactours)
