### ISSUE TITLE
GRUB Theme

### ISSUE THREAD

**Issue by thearctiic** [Avdan-OS/Desktop-environment#12]
Need a GRUB theme to be done alongside the boot screen/animation.

Use the Garuda Dr460nized theme.txt file for reference or for direct editing :)

**Comment by fuwaflow** [comment]
I might work on this

**Comment by ghost** [comment]
and then also implementing it. devs tell who wants tp work on it

**Comment by ghost** [comment]
@LinuxJava7 i have assign it to you

**Comment by thearctiic** [comment]
Implementing the theme is perfectly fine, I can do that

**Comment by ghost** [comment]
Ok
