### ISSUE TITLE
AvdanOS Bootup Animation

### ISSUE THREAD

**Issue by Trynera** [Avdan-OS/Desktop-environment#29]
So the current Bootup Animation is the old AvdanOS logo. Just wanted to point that out lmao

**Comment by StoneMcYT** [comment]
Thanks for pointing out!
I will speak to our design team and try and get it updated soon

**Comment by Golem642** [comment]
> So the current Bootup Animation is the old AvdanOS logo. Just wanted to point that out lmao

Hello, yes i plan to remake the loading animation and the full boot animation concept wit mh the new logo when i get back

**Comment by Cactus500** [comment]
i did it

https://user-images.githubusercontent.com/104501679/185785763-bfb77b63-fb7e-4a05-affa-7d51fa394dcb.mp4

.

**Comment by Golem642** [comment]
Bruh what there are so much things wrong with this

**Comment by Golem642** [comment]
![boot replaced final](https://user-images.githubusercontent.com/65229557/185799185-991db596-529e-4155-afb5-7e006dec9159.gif)
Here's my take

**Comment by Cactus500** [comment]
> ![boot replaced final](https://user-images.githubusercontent.com/65229557/185799185-991db596-529e-4155-afb5-7e006dec9159.gif) Here's my take

wow its really better but, can we get the mp4 file, to get a better quality ?

**Comment by pookiegoescrazy** [comment]
[https://drive.google.com/file/d/1VafO9lOnMZbwPRWeqJkCEbP2VnB77Sdn/view?usp=sharing](url) heres my attempt, its an mp4 and idk how to upload a video on github so have at it
