### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Rohith0009** [Avdan-OS/Desktop-environment#40]
Can i Please join the team when I am 13 I really love this project I want to contribute.
Thanks
-Rohith M

**Comment by Rohith0009** [comment]
but am i allowed to atleast contribute on GitHub

**Comment by Froxcey** [comment]
Yes, definitely. I also want you to be in the project.

> but am i allowed to atleast contribute on GitHub

*~~Breaks GitHub ToS~~* Anyways

**Comment by ghost** [comment]
Sorry but github age requirement is 13 too

**Comment by Rohith0009** [comment]
> Sorry but github age requirement is 13 too

ok I will be inactive on discord too for 5 months
